spring:
  application:
    name: AdventurersGuild
  datasource:
    url: jdbc:postgresql://localhost:5432/ag_db
    username: postgres
    password: 53cr35w4ll0wt41l
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true